Fix missing `u_char' definition error
For older Apple LLVM
/usr/include/sys/kern_control.h:139:5: error: unknown type name 'u_char'; did you mean 'char'?